name: contactstesto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.0
  # contacts_service: ^0.6.3
  firebase_auth: ^5.3.4
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  get: ^4.6.6
  intl: ^0.20.1
  permission_handler: ^11.3.1
  share_plus: ^10.1.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
